mainak2003/WebApp

test.html

(New Feature): Added Navbar and Cards

---

test.html

Added : Get Started Button

---

Contact.html
test.html

Contact Us page added

---

index.html
style.css

Navbar made responsive and added Style.css

Navbar made responsive and added Style.css

---

about.html
index.html

(FIXED) buggy About & Home page

---

about.html
index.html

Major UI Design Improvements : Updated Looks

Major UI Design Improvements : Updated Looks

---

Contact.html

(Fix) Bug: Contact Us Page & Added custom theme

(Fix) Bug: Contact Us Page & Added custom theme

---

testimomial.html
testimonial.css

testimonial page

---

index.html
index[Gaurav].html
styles.css

Please Check out this Styling 
it did give me way too much of a challenge after those 10 conflicts 
i rewrite the whole code again
but did manage to save the previous one 
you can check both decide which is better.
Thanks

Styling Added by Me 

---

Contact.html
about.html
index.html
testimonial.html

Fix issue #18 : Add Search Bar

---

index.html

I've added Scroll to top button. Please review the changes.

Fix issue #22: Scroll to TOP button created

---

index.html
styles.css

I've replaced the old cards section with a new trendy cards design!
BEFORE
NEW
CLOSES ISSUE #25 .

Fix issue #25: Replaced the Old Cards Section with New Trendy Design 

---

login.css
login.html

Final_Commit

---

Contact.html
about.html
index.html
script.js
testimonial.html

Able to generate courses dynamically on the home page.
Alignment of Search bar in nav bar

Code Optimisation, Alignment of serach bar in nav

---

index.html
styles.css
testimonial.css
testimonial.html

updated navbar

---

styles.css

Issue #34 
Added glass morphism effect, scrolling position and alignment changes to navbar

Feature - UI changes on Navbar Added glass morphism effect 

---

index.html

Updated design of back to top button.

Updated designing 

---

index.html

Updated designing for the footer and added a GitHub link.

fix: updated designing for footer

---

index.html
styles.css

[Modify] : Modified buggy buttons to CSS trendy button

---

Contact.html
about.html
styles.css
testimonial.css
testimonial.html

- Fixed Navbar Errors
- Linked CSS files accurately

[Fix] Navbar Errors in All Pages

---

styles.css

Added a scrollbar in the application.
Screenshot:

fix: updated scrollbar of applcation

---

index.html
styles.css

Fixed card theme according to the theme of the website

[Fix]: CSS Card theme according to the theme of the website

---

login.css
login.html

[Improved] : UI of Login & Signup Page
